HTTP_STATUS_SUCCESSFUL = 200
HTTP_STATUS_INTERNAL_ERROR = 500
HTTP_STATUS_EXTERNAL_ERROR = 502

ALIAS_INGESTION_DB='agent-history-db'

CREATE_SESSION_LOG_NAME = 'create-session-v1'
GET_ALL_SESSIONS_LOG_NAME = 'get-all-sessions-v1'
GET_HISTORY_LOG_NAME = 'get-history-v1'
CHAT_LOG_NAME_V1 = 'chat-v1'

MONGODB_CHAT_SESSION_COL = 'chat_session'
MONGODB_CHAT_HISTORY_COL = 'chat_history'
